services:
  laravel:
    environment:
      APP_ENV: staging
      APP_DEBUG: "false"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI:-}
      ORCID_CLIENT_ID: ${ORCID_CLIENT_ID:-}
      ORCID_CLIENT_SECRET: ${ORCID_CLIENT_SECRET:-}
      ORCID_REDIRECT_URI: ${ORCID_REDIRECT_URI:-}
      AUTORUN_ENABLED: "true"
      AUTORUN_LARAVEL_MIGRATION: "true"
      AUTORUN_LARAVEL_MIGRATION_FORCE: "true"
      AUTORUN_LARAVEL_MIGRATION_ISOLATION: "true"
      AUTORUN_LARAVEL_OPTIMIZE: "true"
      AUTORUN_LARAVEL_STORAGE_LINK: "true"
      PHP_OPCACHE_ENABLE: "1"
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"
      PHP_OPCACHE_REVALIDATE_FREQ: "0"
    volumes: &laravel-staging-volumes
      - laravel-storage:/var/www/html/storage

  horizon:
    environment:
      APP_ENV: staging
      APP_DEBUG: "false"
      AUTORUN_ENABLED: "true"
      AUTORUN_LARAVEL_MIGRATION: "false"
      AUTORUN_LARAVEL_OPTIMIZE: "true"
      AUTORUN_LARAVEL_STORAGE_LINK: "false"
      PHP_OPCACHE_ENABLE: "1"
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"
      PHP_OPCACHE_REVALIDATE_FREQ: "0"
    volumes: *laravel-staging-volumes

  scheduler:
    environment:
      APP_ENV: staging
      APP_DEBUG: "false"
      AUTORUN_ENABLED: "true"
      AUTORUN_LARAVEL_MIGRATION: "false"
      AUTORUN_LARAVEL_OPTIMIZE: "true"
      AUTORUN_LARAVEL_STORAGE_LINK: "false"
      PHP_OPCACHE_ENABLE: "1"
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"
      PHP_OPCACHE_REVALIDATE_FREQ: "0"
    volumes: *laravel-staging-volumes

  reverb:
    environment:
      APP_ENV: staging
      APP_DEBUG: "false"
      AUTORUN_ENABLED: "true"
      AUTORUN_LARAVEL_MIGRATION: "false"
      AUTORUN_LARAVEL_OPTIMIZE: "true"
      AUTORUN_LARAVEL_STORAGE_LINK: "false"
      PHP_OPCACHE_ENABLE: "1"
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"
      PHP_OPCACHE_REVALIDATE_FREQ: "0"
    volumes: *laravel-staging-volumes
